### PR TITLE
Lint all liquid comments

### PR DESCRIPTION
**Pull request by nikivazou**

### CODE REVIEW

**Comment by lierdakil** [comment]
Please see https://github.com/atom-haskell/language-haskell/blob/master/CONTRIBUTING.md

**Comment by lierdakil** [comment]
Also, this is probably bad form, since `liquidhaskell_annotation` ends up including `liquidhaskell_annotation`. Besides, I don't think liquidhaskell supports c preprocessor or foreign imports. Maybe *adding* missing scopes instead of *changing* `haskell_expr` to `haskell_toplevel` would be a better approach.

**Comment by nikivazou** [comment]
I agree that this is not totally correct. 
The problem that this edits fixes compared to the previous grammar is that most liquid annotations are not colored and I really do not understand which are and which are not. 

I guess the proper solution will be to define a new liquid grammar that includes exactly what Liquid Haskell supports.

**Comment by lierdakil** [comment]
Disclamer: I have close to zero knowledge on liquidhaskell, and also I'm not entirely sober at the moment

I would assume that LH uses mostly Haskell syntax. If so, you *probably* just need to add missing scopes from https://github.com/atom-haskell/language-haskell/blob/master/src/include/repository.coffee#L595 before `haskell_expr`. Since I have no idea what liquidhaskell actually allows, I can't choose myself, but I would guess maybe `class_decl` (which highlights `class ... where`), probably `instance_decl` (which highlights `instance ... where`), `data_decl` (which highlights `data ... =`/`newtype ... =`) and `type_alias` (which highlights `type ... =` and also type families and instances). The rest are responsible for standalone deriving, foreign and regular imports and C preprocessor directives, which I would assume are inapplicable to LH

**Comment by lierdakil** [comment]
Due to no response from OP, @ranjitjhala, could you possibly give a short overview of what is allowed inside LH annotations?

**Comment by ranjitjhala** [comment]
Sure, in brief, most annotations look like:

```
[KEYWORD] identifier :: liquidType 
```

i.e. like haskell type annotations with an optional keyword (which I am happy to enumerate),

A `liquidType` looks roughly like this, wherever you have a haskell type `T`, you can now 
have something like `{v:T | e}` where 

* `v` is a haskell identifier (e.g. `x`, `y`, `v` etc.)
* `T` is a haskell type (e.g. `Int`, `String` etc.)
* `e` is a haskell expression (e.g. `0 < x`)

Consequently, I have found that _mostly_ simply treating the stuff inside 
annotations as plain Haskell code (i.e. highlighting the code inside with
the usual haskell-grammar  i.e. `haskell_expr`) has been working pretty 
well IMO.

There are some other things like `data`/`class` definitions that are not 
handled by `haskell_expr` and for that I think @lierdakil 's suggestion 
of adding `class_decl`, `instance_decl` and `data_decl` makes perfect 
sense. I agree also that adding the full `top_level` is overkill and may 
cause weird problems.

Maybe @nikivazou can you:

1. Create a bunch of example files with the stuff you want to see highlighted,
2. Check whether adding the above grammars per @lierdakil 's suggestion does the trick 

If so, you can suitably update the PR, and if not, we can see what needs to be done from there?

Thanks for the suggestions @lierdakil !!!

**Comment by lierdakil** [comment]
Okay, so I had some time to investigate further, and found a couple scope leaks in existing grammar. So I've made some changes to combat that, hopefully without breaking something else.

Additionally, I've tried to add some more or less correct highlighting for "liquid types" (i.e. `{ v:T | e }`, `{ e }` and `v:T`), but that might go awry in some cases, and will have some problems with line breaks (limitation of grammar model). Reports are greatly appreciated.

So everything's released as v1.14.0. Bear in mind it can take a while to get into GitHub's system.

@nikivazou, if you could confirm that v1.14.0 works for you, that would be nice. If you find something that doesn't work as you expect it to, feel free to open new issues. Thanks.

**Comment by ranjitjhala** [comment]
Wow, this is awesome, thanks @lierdakil !!!!

**Comment by nikivazou** [comment]
Thanks **a lot**!!!

Looks great! Will let you know in a different issue if I have new requests. We can close this one!

Thanks!

**Pull request closed without merging**
