### PR TITLE
Rename deprecated `scoped-properties` to `settings`.

### PR DESCRIPTION
**Pull request by ijuma**
The deprecation message says:

"Store package settings files in the `settings/` directory instead of `scoped-properties/`"

More information: https://atom.io/docs/latest/upgrading/upgrading-your-package

### CODE REVIEW

**Comment by JonMidhir** [comment]
+1 PLEASE merge this & repackage

**Comment by Gwnl** [comment]
Please merge!

**Comment by mc10** [comment]
@jroesch It would be great if this got merged in, as v1.0.0 will completely remove deprecated features. This PR also fixes #15, #17, #18, #20, #22, #24, #25, and #27, and closes #19, so those issues/PRs should be closed when this gets merged in.

**Comment by rossmcf** [comment]
+1 I hate those pesky deprecation messages.

**Comment by kRITZCREEK** [comment]
:+1

**Comment by RodrigoEspinosa** [comment]
:+1:

**Comment by JonMidhir** [comment]
:+1: _please_

**Comment by rpowelll** [comment]
:+1:

**Comment by impinball** [comment]
Please version-bump this, so it'll trigger an update.

**Comment by lierdakil** [comment]
Fixed by v1.0.2

**Pull request closed without merging**
